services:
  auth_db:
    image: postgres:15
    container_name: auth_db
    environment:
      POSTGRES_DB: banking-auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  auth_service:
    image: haranton/authservice:latest
    depends_on:
      - auth_db
    restart: on-failure
    ports:
      - "8080:8080"
    command: ["./main", "--config=./config/local.yaml"]

volumes:
  postgres_data:
